#!/bin/bash

# minecraft server for fun

echo "Choose which world to launch:"
echo
echo "  (1): world"
echo "  (2): world2"
echo "  (2): world3"
echo
echo -n "SELECT: "
read choice

cd ~/Minecraft

# set level-name to correct world
case "$choice" in
	[1])
		sed -i 's;level-name=.*;level-name=world;' server.properties
		;;
	[2])
		sed -i 's;level-name=.*;level-name=world2;' server.properties
		;;
	[3])
                sed -i 's;level-name=.*;level-name=world3;' server.properties
                ;;
	*)
		echo "Ayyyy lmao you can't choose '$choice'"
		echo "cya sucker!"
		exit 1
esac

# RUN THE GAME!!!
java -Xmx1024M -Xms1024M -jar minecraft_server.1.15.2.jar nogui

cd -
