#!/bin/bash

# This is a script to run either a TTT server or GMOD Sandbox server

clear

echo "Which mode would you like to play?"
echo
echo "  (S): Sandbox"
echo "  (T): Trouble in Terrorist Town"
#echo "  (D): DarkRP (Experimental)"
#echo "  (F): Surf   (Experimental)"
echo "  (H): Horror"
echo "  (M): Murder"
echo
echo "The choice is yours..."
echo -n "ENTER (and ya better not screw it up): "
read choice

clear

case "$choice" in
	[Tt])
		echo "Starting TTT server..."
		~/GMOD/srcds_run -game garrysmod +maxplayers 20 +gamemode terrortown +map ttt_waterworld +host_workshop_collection 585606511 -authkey FB042995BFC7F304265DAB02D07A70C0
		;;
	[Ss])
		echo "Starting Sandbox server..."
		~/GMOD/srcds_run -game garrysmod +maxplayers 20 +gamemode sandbox +map gm_construct +host_workshop_collection 621248766 -authkey FB042995BFC7F304265DAB02D07A70C0
		;;
#	[Dd])
 #		echo "Starting DarkRP server..."
  #		~/GMOD/srcds_run -game garrysmod +maxplaters 12 +gamemode darkrp +map rp_downtown_v4c_v2 +host_workshop_collection 585606511 -authkey FB042995BFC7F304265DAB02D07A70C0
   #		;;
#	[Ff])
 #               echo "Starting Surf server..."
  #              ~/GMOD/srcds_run -game garrysmod +maxplaters 12 +gamemode sandbox +map gm_construct +host_workshop_collection 585606511 -authkey FB042995BFC7F304265DAB02D07A70C0
   #             ;;
	[Hh])
		echo "Starting Horror server..."
		~/GMOD/srcds_run -game garrysmod +maxplayers 20 +gamemode horror +map gmi_hunt +host_workshop_collection 1695067340 -authkey FB042995BFC7F304265DAB02D07A70C0
		;;
	[Mm])
		echo "Starting Murder server..."
		~/GMOD/srcds_run -game garrysmod +maxplayers 20 +gamemode murder +map mu_office +host_workshop_collection 621248766 -authkey FB042995BFC7F304265DAB02D07A70C0
		;;
	*)
		echo "USAGE: dude, just enter a REAL CHOICE, ur bad nerd"
		echo
		exit 1
esac

clear
